src/objects/Doc_Field__c.object
<CustomObject>
    <fields>
        <fullName>Doc_SObject__c</fullName>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Doc SObject</label>
        <referenceTo>Doc_SObject__c</referenceTo>
        <relationshipLabel>Doc Fields</relationshipLabel>
        <relationshipName>Doc_Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExtId__c</fullName>
        <description>System generated</description>
        <externalId>true</externalId>
        <inlineHelpText>System generated</inlineHelpText>
        <label>ExtId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IsCustom__c</fullName>
        <defaultValue>false</defaultValue>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Is Custom</label>
        <type>Checkbox</type>
    </fields>
    <label>Doc Field</label>
    <nameField>
        <label>Doc Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doc Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Doc_SObject__c.object
<CustomObject>
    <fields>
        <fullName>IsCustom__c</fullName>
        <defaultValue>true</defaultValue>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Is Custom</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Namespace__c</fullName>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Namespace</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VIPForm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Object</label>
    <nameField>
        <label>SObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Doc_SObject.cls
public class Doc_SObject {

    private List<SObjectType> sobjectTypes = new List<SObjectType>();
    
    public Doc_SObject() {
        this.sobjectTypes = Schema.getGlobalDescribe().values();
    }
    
    public void analyze() {
        List<Doc_SObject__c> doc_SObjects = new List<Doc_SObject__c>();
        List<Doc_Field__c> doc_Fields = new List<Doc_Field__c>();
        for(SObjectType sobjectType : this.sobjectTypes) {
            //if(!sobjectType.getDescribe().isCustom()) continue;

            doc_SObjects.add(new Doc_SObject__c(
                ExtId__c = sobjectType.getDescribe().getName(),
                IsCustom__c = sobjectType.getDescribe().isCustom(),
                Name     = sobjectType.getDescribe().getName(),
                Namespace__c = this.getNamespace(sobjectType)
            ));
            
            for(SObjectField field : sobjectType.getDescribe().fields.getMap().values()) {
                doc_Fields.add(new Doc_Field__c(
                    //IsCustom__c = field.getDescribe().isCustom(),
                	ExtId__c = sobjectType.getDescribe().getName() + '.' + field.getDescribe().getName(),
                    Doc_SObject__r = new Doc_SObject__c(ExtId__c = sobjectType.getDescribe().getName()),
                    Name = field.getDescribe().getName()
                ));
            }
        }
        upsert doc_SObjects ExtId__c;
        upsert doc_Fields ExtId__c;
    }
    
    private String getNamespace(Schema.SObjectType sobjectType) {
        String fullApiName = sobjectType.getDescribe().getName();
        Integer localNameIndex = fullApiName.replace('__c', '').indexOf('__');
        return localNameIndex < 0 ? null : fullApiName.substring(0, localNameIndex);
	}
    
}