src/objects/Doc_Field__c.object
<CustomObject>
    <fields>
        <fullName>Doc_SObject__c</fullName>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Doc SObject</label>
        <referenceTo>Doc_SObject__c</referenceTo>
        <relationshipLabel>Doc Fields</relationshipLabel>
        <relationshipName>Doc_Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>InlineHelpText__c</fullName>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Inline Help Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IsCustom__c</fullName>
        <defaultValue>false</defaultValue>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Is Custom</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Length</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PicklistValues__c</fullName>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Picklist Values</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>address</fullName>
                </value>
                <value>
                    <fullName>anytype</fullName>
                </value>
                <value>
                    <fullName>base64</fullName>
                </value>
                <value>
                    <fullName>Boolean</fullName>
                </value>
                <value>
                    <fullName>Combobox</fullName>
                </value>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>DataCategoryGroupReference</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>DateTime</fullName>
                </value>
                <value>
                    <fullName>Double</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>EncryptedString</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>Integer</fullName>
                </value>
                <value>
                    <fullName>Long</fullName>
                </value>
                <value>
                    <fullName>MultiPicklist</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Reference</fullName>
                </value>
                <value>
                    <fullName>String</fullName>
                </value>
                <value>
                    <fullName>TextArea</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
                <value>
                    <fullName>URL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Doc Field</label>
    <nameField>
        <label>Doc Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doc Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Doc_RecordType__c.object
<CustomObject>
    <fields>
        <fullName>Doc_SObject__c</fullName>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Doc SObject</label>
        <referenceTo>Doc_SObject__c</referenceTo>
        <relationshipLabel>Doc Record Types</relationshipLabel>
        <relationshipName>Doc_Record_Types</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsMaster__c</fullName>
        <defaultValue>false</defaultValue>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Is Master</label>
        <type>Checkbox</type>
    </fields>
    <label>Doc Record Type</label>
    <nameField>
        <label>Doc Record Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doc Record Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Doc_SObject__c.object
<CustomObject>
    <fields>
        <fullName>DeveloperName__c</fullName>
        <description>System generated</description>
        <externalId>true</externalId>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Developer Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>InScope__c</fullName>
        <formula>OR(
    IsClosed__c = false,
    TEXT(Status__c) = &apos;Approved&apos;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>In Scope</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsCustomSetting__c</fullName>
        <defaultValue>false</defaultValue>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Is Custom Setting</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsCustom__c</fullName>
        <defaultValue>true</defaultValue>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Is Custom</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsPlatformFeatureObject__c</fullName>
        <description>System generated</description>
        <formula>OR(
    IsChangeEvent__c,    
    IsChatterFeedObject__c,
    IsHistoryObject__c,
    IsShareObject__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Is Platform Feature Object</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LabelLanguage__c</fullName>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Label Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>en_US</fullName>
                    <default>true</default>
                    <label>en_US</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LabelPlural__c</fullName>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Label Plural</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>System generated.</description>
        <inlineHelpText>System generated.</inlineHelpText>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastMetadataChangeDate__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Last Metadata Change Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Namespace__c</fullName>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Namespace</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VIPForm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ParentSObject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>System generated.</description>
        <inlineHelpText>System generated.</inlineHelpText>
        <label>Parent SObject</label>
        <referenceTo>Doc_SObject__c</referenceTo>
        <relationshipName>PlatformFeatureObjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SystemHashCode__c</fullName>
        <description>System generated.</description>
        <inlineHelpText>System generated.</inlineHelpText>
        <label>System Hash Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Object</label>
    <nameField>
        <label>SObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objects</pluralLabel>
    <recordTypes>
        <fullName>Asset</fullName>
        <active>true</active>
        <description>Design &amp; config have been started</description>
        <label>Object Asset</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Doc_SObjectBatch.cls
public class Doc_SObjectBatch implements Database.Batchable<Schema.SObjectType> {

    private static final Set<Schema.SObjectType> IGNORED_SOBJECT_TYPES = new Set<Schema.SObjectType>{
        Schema.ApexClass.SObjectType, Schema.ApexComponent.SObjectType, Schema.ApexEmailNotification.SObjectType,
        Schema.ApexLog.SObjectType, Schema.ApexPage.SObjectType, Schema.ApexPageInfo.SObjectType,
        Schema.ApexTestQueueItem.SObjectType, Schema.ApexTestResult.SObjectType, Schema.ApexTestResultLimits.SObjectType,
        Schema.ApexTestRunResult.SObjectType, Schema.ApexTestSuite.SObjectType, Schema.ApexTrigger.SObjectType,
        Schema.AuraDefinition.SObjectType, Schema.AuraDefinitionBundle.SObjectType,
        Schema.AuraDefinitionBundleInfo.SObjectType, Schema.AuraDefinitionInfo.SObjectType,
        Schema.BatchApexErrorEvent.SObjectType
    };

    public Iterable<Schema.SObjectType> start(Database.BatchableContext batchableContext) {
        List<Schema.SObjectType> sobjectTypesToProcess = new List<Schema.SObjectType>();
        for(Schema.SObjectType sobjectType : Schema.getGlobalDescribe().values()) {
            if(IGNORED_SOBJECT_TYPES.contains(sobjectType)) continue;
            else sobjectTypesToProcess.add(sobjectType);
        }
        return sobjectTypesToProcess;
    }

    public void execute(Database.BatchableContext batchableContext, List<Schema.SObjectType> scope) {
        Map<String, Doc_SObject__c> existingSObjectTypesByApiName = this.getExistingSObjectTypesByApiName();

        this.analyze(scope, existingSObjectTypesByApiName);
    }

    public void finish(Database.BatchableContext batchableContext) {}

    private Map<String, Doc_SObject__c> getExistingSObjectTypesByApiName() {
        Map<String, Doc_SObject__c> existingSObjectTypesByApiName = new Map<String, Doc_SObject__c>();
        for(Doc_SObject__c docSObject : [SELECT Id, Name, DeveloperName__c, SystemHashCode__c, InScope__c FROM Doc_SObject__c]) {
            existingSObjectTypesByApiName.put(docSObject.DeveloperName__c, docSObject);
        }
        return existingSObjectTypesByApiName;
    }

    private void analyze(List<Schema.SObjectType> sobjectTypes, Map<String, Doc_SObject__c> getExistingSObjectTypesByApiName) {
        List<Doc_SObject__c> doc_SObjects       = new List<Doc_SObject__c>();
        List<Doc_Field__c> doc_Fields           = new List<Doc_Field__c>();
        List<Doc_RecordType__c> doc_RecordTypes = new List<Doc_RecordType__c>();

        for(SObjectType sobjectType : sobjectTypes) {
            Schema.DescribeSObjectResult sobjectDescribe = sobjectType.getDescribe();

            Doc_SObject__c existingDocSObject = getExistingSObjectTypesByApiName.get(sobjectDescribe.getName());

            // Skip if this SObject Type has already been flagged with status = 'Not Used'
            if(existingDocSObject != null && existingDocSObject.InScope__c == false) continue;

            Doc_SObject__c docSObject = new Doc_SObject__c(
                DeveloperName__c   = sobjectDescribe.getName(),
                IsCustom__c        = sobjectDescribe.isCustom(),
                IsCustomSetting__c = sobjectDescribe.isCustomSetting(),
                Label__c           = sobjectDescribe.getLabel(),
                LabelPlural__c     = sobjectDescribe.getLabelPlural(),
                LabelLanguage__c   = UserInfo.getLanguage(),
                Name               = sobjectDescribe.getName(),
                Namespace__c       = this.getNamespace(sobjectDescribe),
                RecordTypeId       = this.getAssetRecordTypeId(Schema.Doc_SObject__c.SObjectType)
            );

            // Link to parent object -- TODO, improve this/move to private method
            docSObject.recalculateFormulas();
            List<String> testFeatureObjects = new List<String>{'AccountFeed', 'AccountHistory'};
            if(docSObject.IsPlatformFeatureObject__c && testFeatureObjects.contains(docSObject.Name)) {
                docSObject.ParentSObject__r = new Doc_SObject__c(DeveloperName__c = 'Account');
            }

            // TODO move to private method
            docSObject.SystemHashCode__c = System.hashCode(docSObject);
            if(existingDocSObject != null && existingDocSObject.SystemHashCode__c != docSObject.SystemHashCode__c) {
                docSObject.LastMetadataChangeDate__c = System.now();
            }

            doc_SObjects.add(docSObject);

            for(SObjectField field : sobjectDescribe.fields.getMap().values()) {
                Schema.DescribeFieldResult fieldDescribe = field.getDescribe();

                doc_Fields.add(new Doc_Field__c(
                    DefaultValue__c         = String.valueOf(fieldDescribe.getDefaultValue()),
                    Digits__c               = fieldDescribe.getDigits(),
                    Doc_SObject__r          = new Doc_SObject__c(DeveloperName__c = sobjectDescribe.getName()),
                    DeveloperName__c        = sobjectDescribe.getName() + '.' + fieldDescribe.getName(),
                    InlineHelpText__c       = fieldDescribe.getInlineHelpText(),
                    IsCustom__c             = fieldDescribe.isCustom(),
                    IsNillable__c           = fieldDescribe.isNillable(),
                    IsPermissionable__c     = fieldDescribe.isPermissionable(),
                    IsRestrictedDelete__c   = fieldDescribe.isRestrictedDelete(),
                    IsRestrictedPicklist__c = fieldDescribe.isRestrictedPicklist(),
                    IsUnique__c             = fieldDescribe.isUnique(),
                    Label__c                = fieldDescribe.getLabel(),
                    Length__c               = fieldDescribe.getLength(),
                    Name                    = fieldDescribe.getName(),
                    Namespace__c            = this.getNamespace(fieldDescribe),
                    PicklistValues__c       = this.getPicklistValueString(field),
                    Precision__c            = fieldDescribe.getPrecision(),
                    RecordTypeId            = this.getAssetRecordTypeId(Schema.Doc_Field__c.SObjectType),
                    ReferenceTo__c          = this.getReferenceToValueString(fieldDescribe),
                    RelationshipName__c     = fieldDescribe.getRelationshipName(),
                    Scale__c                = fieldDescribe.getScale(),
                    Type__c                 = fieldDescribe.getType().name()
                ));
            }

            for(Schema.RecordTypeInfo recordTypeInfo : sobjectDescribe.getRecordTypeInfosByDeveloperName().values()) {
                if(recordTypeInfo.isMaster()) continue; // TODO for now, don't log master record types. Might change later

                doc_RecordTypes.add(new Doc_RecordType__c(
                    Doc_SObject__r   = new Doc_SObject__c(DeveloperName__c = sobjectType.getDescribe().getName()),
                    DeveloperName__c = sobjectType.getDescribe().getName() + '.' + recordTypeInfo.getDeveloperName(),
                    IsActive__c      = recordTypeInfo.isActive(),
                    IsMaster__c      = recordTypeInfo.isMaster(),
                    Name             = recordTypeInfo.getDeveloperName(),
                    Namespace__c     = this.getNamespace(recordTypeInfo),
                    RecordTypeId     = this.getAssetRecordTypeId(Schema.Doc_RecordType__c.SObjectType)
                ));
            }
        }
        upsert doc_SObjects DeveloperName__c;
        upsert doc_Fields DeveloperName__c;
        upsert doc_RecordTypes DeveloperName__c;
    }

    private Id getAssetRecordTypeId(Schema.SObjectType sobjectType) {
        return sobjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Asset').getRecordTypeId();
    }

    private String getNamespace(Schema.DescribeSObjectResult sobjectDescribe) {
        return this.getNameSpace(sobjectDescribe.getName());
    }

    private String getNamespace(Schema.DescribeFieldResult fieldDescribe) {
        return this.getNameSpace(fieldDescribe.getName());
    }

    private String getNameSpace(Schema.RecordTypeInfo recordTypeInfo) {
        return this.getNamespace(recordTypeInfo.getDeveloperName());
    }

    private String getNamespace(String fullApiName) {
        Integer localNameIndex = fullApiName
            .replace('__c', '')           // Custom objects & custom settings
            .replace('__e', '')           // Custom platform events
            .replace('__mdt', '')         // Custom metadata types
            .replace('__ChangeEvent', '') // Standard platform events
            .replace('__Feed', '')        // Chatter feed
            .replace('__History', '')     // History object
            .indexOf('__');               // Now we can determine if there is a namespace

        return localNameIndex < 0 ? null : fullApiName.substring(0, localNameIndex);
    }

    private String getReferenceToValueString(Schema.DescribeFieldResult fieldDescribe) {
        List<String> values = new List<String>();
        for(Schema.SObjectType sobjectType : fieldDescribe.getReferenceTo()) {
            values.add(sobjectType.getDescribe().getName());
        }
        return String.join(values, '\n');
    }

    private String getPicklistValueString(Schema.SObjectField field) {
        String valueString = String.join(this.getPicklistValues(field), '\n');
        if(valueString.length() > field.getDescribe().getLength()) return 'Too many values';
        return valueString;
    }

    private List<String> getPicklistValues(Schema.SObjectField field) {
        Schema.DescribeFieldResult fieldDescribe = field.getDescribe();
        List<String> picklistValues = new List<String>();

        if(fieldDescribe.getPickListValues().isEmpty()) return picklistValues;

        for(Schema.PicklistEntry picklistEntry : fieldDescribe.getPickListValues()) {
            picklistValues.add(picklistEntry.getValue());
        }
        return picklistValues;
    }

}