src/objects/ExternalSystem__c.object
<CustomObject>
    <fields>
        <fullName>IsInScope__c</fullName>
        <formula>OR(
    IsClosed__c = false,
    TEXT(Status__c) = &apos;Done&apos;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is In Scope</label>
        <type>Checkbox</type>
    </fields>
    <label>External System</label>
    <nameField>
        <label>External System</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ExternalSystemField__c.object
<CustomObject>
    <fields>
        <fullName>IsInScope__c</fullName>
        <formula>OR(
    IsClosed__c = false,
    TEXT(Status__c) = &apos;Done&apos;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is In Scope</label>
        <type>Checkbox</type>
    </fields>
    <label>External System Field</label>
    <nameField>
        <displayFormat>ExtField-{00000}</displayFormat>
        <label>External Field Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External System Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MetadataField__c.object
<CustomObject>
    <fields>
        <fullName>DeveloperName__c</fullName>
        <description>System generated</description>
        <externalId>true</externalId>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Developer Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IsCustom__c</fullName>
        <defaultValue>true</defaultValue>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Is Custom</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsInScope__c</fullName>
        <formula>OR(
    IsClosed__c = false,
    TEXT(Status__c) = &apos;Approved&apos;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is In Scope</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>System generated. Returns the text label that is displayed next to the field in the Salesforce user interface. This label can be localized.</description>
        <inlineHelpText>System generated. Returns the text label that is displayed next to the field in the Salesforce user interface. This label can be localized.</inlineHelpText>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastMetadataChangeDate__c</fullName>
        <label>Last Metadata Change Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MetadataSObject__c</fullName>
        <label>SObject</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>MetadataSObject__c.IsInScope__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>MetadataSObject__c</referenceTo>
        <relationshipLabel>Fields</relationshipLabel>
        <relationshipName>MetadataFields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Namespace__c</fullName>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Namespace</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>IsCalculated__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>address</fullName>
                </value>
                <value>
                    <fullName>anytype</fullName>
                </value>
                <value>
                    <fullName>base64</fullName>
                </value>
                <value>
                    <fullName>Boolean</fullName>
                </value>
                <value>
                    <fullName>Combobox</fullName>
                </value>
                <value>
                    <fullName>ComplexValue</fullName>
                </value>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>DataCategoryGroupReference</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>DateTime</fullName>
                </value>
                <value>
                    <fullName>Double</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>EncryptedString</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>Integer</fullName>
                </value>
                <value>
                    <fullName>Location</fullName>
                </value>
                <value>
                    <fullName>Long</fullName>
                </value>
                <value>
                    <fullName>MultiPicklist</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Reference</fullName>
                </value>
                <value>
                    <fullName>String</fullName>
                </value>
                <value>
                    <fullName>TextArea</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
                <value>
                    <fullName>URL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <recordTypes>
        <fullName>Asset</fullName>
        <active>true</active>
        <description>Design &amp; config have been started</description>
        <label>Asset</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MetadataRecordType__c.object
<CustomObject>
    <fields>
        <fullName>DeveloperName__c</fullName>
        <description>System generated</description>
        <externalId>true</externalId>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Developer Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsCustom__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Custom</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsInScope__c</fullName>
        <formula>OR(
    IsClosed__c = false,
    TEXT(Status__c) = &apos;Approved&apos;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is In Scope</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MetadataSObject__c</fullName>
        <label>SObject</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>MetadataSObject__c.IsInScope__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>MetadataSObject__c</referenceTo>
        <relationshipLabel>Record Types</relationshipLabel>
        <relationshipName>MetadataRecordTypes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Namespace__c</fullName>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Namespace</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Record Type</label>
    <nameField>
        <label>Record Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Record Types</pluralLabel>
    <recordTypes>
        <fullName>Asset</fullName>
        <active>true</active>
        <description>Design &amp; config have been started</description>
        <label>Asset</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MetadataSObject__c.object
<CustomObject>
    <fields>
        <fullName>DeveloperName__c</fullName>
        <description>System generated</description>
        <externalId>true</externalId>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Developer Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IsCustomSetting__c</fullName>
        <defaultValue>false</defaultValue>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Is Custom Setting</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsCustom__c</fullName>
        <defaultValue>true</defaultValue>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Is Custom</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsInScope__c</fullName>
        <formula>OR(
    IsClosed__c = false,
    TEXT(Status__c) = &apos;Done&apos;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is In Scope</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsPlatformFeatureObject__c</fullName>
        <description>System generated</description>
        <formula>OR(
    IsChangeEvent__c,    
    IsChatterFeedObject__c,
    IsHistoryObject__c,
    IsShareObject__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Is Platform Feature Object</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LabelLanguage__c</fullName>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Label Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>en_US</fullName>
                    <default>true</default>
                    <label>en_US</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LabelPlural__c</fullName>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Label Plural</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>System generated.</description>
        <inlineHelpText>System generated.</inlineHelpText>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastMetadataChangeDate__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Last Metadata Change Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Namespace__c</fullName>
        <description>System generated</description>
        <inlineHelpText>System generated</inlineHelpText>
        <label>Namespace</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PrimaryMetadataSObject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>System generated.</description>
        <inlineHelpText>System generated.</inlineHelpText>
        <label>Primary SObject</label>
        <referenceTo>MetadataSObject__c</referenceTo>
        <relationshipLabel>Platform Feature SObjects</relationshipLabel>
        <relationshipName>PlatformFeatureSObjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SystemHashCode__c</fullName>
        <description>System generated.</description>
        <inlineHelpText>System generated.</inlineHelpText>
        <label>System Hash Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SObject</label>
    <nameField>
        <label>SObject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SObjects</pluralLabel>
    <recordTypes>
        <fullName>Asset</fullName>
        <active>true</active>
        <description>Design &amp; config have been started</description>
        <label>Asset</label>
    </recordTypes>
    <recordTypes>
        <fullName>PlatformFeatureAsset</fullName>
        <active>true</active>
        <label>Platform Feature</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MetadataSObjectAnalyzer.cls
/*****************************************************************************************************************
* This file is part of the Metadata Dictionary project for Salesforce, released under the MIT License.           *
* See LICENSE file or go to https://github.com/jongpie/SalesforceMetadataDictionary for full license details.    *
*****************************************************************************************************************/
public class MetadataSObjectAnalyzer implements Database.Batchable<Schema.SObjectType> {

    private static final String ASSET_DEVELOPER_NAME                  = 'Asset';
    private static final String PLATFORM_FEATURE_ASSET_DEVELOPER_NAME = 'PlatformFeatureAsset';

    public Iterable<Schema.SObjectType> start(Database.BatchableContext batchableContext) {
        List<Schema.SObjectType> sobjectTypesToProcess = new List<Schema.SObjectType>();
        for(Schema.SObjectType sobjectType : Schema.getGlobalDescribe().values()) {
            String sobjectDeveloperName = sobjectType.getDescribe().getName();

            if(this.getIgnoredSObjectDeveloperNames().contains(sobjectDeveloperName)) continue;
            else sobjectTypesToProcess.add(sobjectType);
        }
        return sobjectTypesToProcess;
    }

    public void execute(Database.BatchableContext batchableContext, List<Schema.SObjectType> scope) {
        Map<String, MetadataSObject__c> existingSObjectTypesByDeveloperName = this.getExistingSObjectTypesByDeveloperName();

        List<MetadataSObject__c> metadataSObjects                = new List<MetadataSObject__c>();
        List<MetadataSObject__c> metadataPlatformFeatureSObjects = new List<MetadataSObject__c>();
        List<MetadataField__c> metadataFields                    = new List<MetadataField__c>();
        List<MetadataRecordType__c> metadataRecordTypes          = new List<MetadataRecordType__c>();

        for(SObjectType sobjectType : scope) {
            Schema.DescribeSObjectResult sobjectDescribe = sobjectType.getDescribe();

            MetadataSObject__c existingMetadataSObject = existingSObjectTypesByDeveloperName.get(sobjectDescribe.getName());

            // Skip if this SObject Type has already been flagged with status = 'Not Used'
            if(existingMetadataSObject != null && existingMetadataSObject.IsInScope__c == false) continue;

            MetadataSObject__c metadataSObject = new MetadataSObject__c(
                DeveloperName__c   = sobjectDescribe.getName(),
                IsCustom__c        = sobjectDescribe.isCustom(),
                IsCustomSetting__c = sobjectDescribe.isCustomSetting(),
                Label__c           = sobjectDescribe.getLabel(),
                LabelPlural__c     = sobjectDescribe.getLabelPlural(),
                LabelLanguage__c   = UserInfo.getLanguage(),
                Name               = sobjectDescribe.getName(),
                Namespace__c       = this.getNamespace(sobjectDescribe),
                RecordTypeId       = this.getRecordTypeId(Schema.MetadataSObject__c.SObjectType, ASSET_DEVELOPER_NAME)
            );

            // Link to parent object -- TODO, improve this/move to private method
            metadataSObject.recalculateFormulas();
            //List<String> testFeatureObjects = new List<String>{'AccountFeed', 'AccountHistory'};
            if(metadataSObject.IsPlatformFeatureObject__c == false) {//} && testFeatureObjects.contains(metadataSObject.Name)) {
                metadataSObjects.add(metadataSObject);
            } else {
                String primarySObjectDeveloperName = this.getPrimarySObjectDeveloperName(sobjectType);

                if(primarySObjectDeveloperName != null) {
                    metadataSObject.PrimaryMetadataSObject__r = new MetadataSObject__c(DeveloperName__c = primarySObjectDeveloperName);
                }
                metadataSObject.RecordTypeId = this.getRecordTypeId(Schema.MetadataSObject__c.SObjectType, PLATFORM_FEATURE_ASSET_DEVELOPER_NAME);
                metadataPlatformFeatureSObjects.add(metadataSObject);
            }

            // TODO move to private method
            metadataSObject.SystemHashCode__c = System.hashCode(metadataSObject);
            if(existingMetadataSObject != null && existingMetadataSObject.SystemHashCode__c != metadataSObject.SystemHashCode__c) {
                metadataSObject.LastMetadataChangeDate__c = System.now();
            }

            for(Schema.RecordTypeInfo recordTypeInfo : sobjectDescribe.getRecordTypeInfosByDeveloperName().values()) {
                if(recordTypeInfo.isMaster()) continue; // TODO for now, don't log master record types. Might change later

                metadataRecordTypes.add(new MetadataRecordType__c(
                    MetadataSObject__r = new MetadataSObject__c(DeveloperName__c = sobjectType.getDescribe().getName()),
                    DeveloperName__c   = sobjectType.getDescribe().getName() + '.' + recordTypeInfo.getDeveloperName(),
                    IsActive__c        = recordTypeInfo.isActive(),
                    IsMaster__c        = recordTypeInfo.isMaster(),
                    Name               = recordTypeInfo.getDeveloperName(),
                    Namespace__c       = this.getNamespace(recordTypeInfo),
                    RecordTypeId       = this.getRecordTypeId(Schema.MetadataRecordType__c.SObjectType, ASSET_DEVELOPER_NAME)
                ));
            }

            for(SObjectField field : sobjectDescribe.fields.getMap().values()) {
                Schema.DescribeFieldResult fieldDescribe = field.getDescribe();

                metadataFields.add(new MetadataField__c(
                    DefaultValue__c         = String.valueOf(fieldDescribe.getDefaultValue()),
                    Digits__c               = fieldDescribe.getDigits(),
                    MetadataSObject__r      = new MetadataSObject__c(DeveloperName__c = sobjectDescribe.getName()),
                    DeveloperName__c        = sobjectDescribe.getName() + '.' + fieldDescribe.getName(),
                    InlineHelpText__c       = fieldDescribe.getInlineHelpText(),
                    IsCalculated__c         = fieldDescribe.isCalculated(),
                    IsCustom__c             = fieldDescribe.isCustom(),
                    IsExternalId__c         = fieldDescribe.IsExternalId(),
                    IsNillable__c           = fieldDescribe.isNillable(),
                    IsPermissionable__c     = fieldDescribe.isPermissionable(),
                    IsRestrictedDelete__c   = fieldDescribe.isRestrictedDelete(),
                    IsRestrictedPicklist__c = fieldDescribe.isRestrictedPicklist(),
                    IsUnique__c             = fieldDescribe.isUnique(),
                    Label__c                = fieldDescribe.getLabel(),
                    Length__c               = fieldDescribe.getLength(),
                    Name                    = fieldDescribe.getName(),
                    Namespace__c            = this.getNamespace(fieldDescribe),
                    PicklistValues__c       = this.getPicklistValueString(field),
                    Precision__c            = fieldDescribe.getPrecision(),
                    RecordTypeId            = this.getRecordTypeId(Schema.MetadataField__c.SObjectType, ASSET_DEVELOPER_NAME),
                    ReferenceTo__c          = this.getReferenceToValueString(fieldDescribe),
                    RelationshipName__c     = fieldDescribe.getRelationshipName(),
                    Scale__c                = fieldDescribe.getScale(),
                    Type__c                 = fieldDescribe.getType().name()
                ));
            }
        }
        upsert metadataSObjects DeveloperName__c;
        upsert metadataPlatformFeatureSObjects DeveloperName__c;
        upsert metadataRecordTypes DeveloperName__c;
        upsert metadataFields DeveloperName__c;
    }

    public void finish(Database.BatchableContext batchableContext) {}

    private Set<String> getIgnoredSObjectDeveloperNames() {
        // These need to be tracked as strings instead of SObjectType because the objects may not exist in all orgs, but if they do exist, we want to ignore them
        Set<String> ignoredSObjectDeveloperNames = new Set<String>{
            'Aggregateresult', 'ApexClass', 'ApexComponent', 'ApexEmailNotification', 'ApexLog', 'ApexPage', 'ApexPageInfo', 'ApexTestQueueItem', 'ApexTestResult',
            'ApexTestResultLimits', 'ApexTestRunResult', 'ApexTestSuite', 'ApexTrigger', 'AppDefinition', 'AppMenuItem', 'AppTabMember', 'AsyncApexJob', 'AuraDefinition',
            'AuraDefinitionBundle', 'AuraDefinitionBundleInfo', 'AuraDefinitionInfo', 'AuthConfig', 'AuthConfigProviders', 'AuthProvider', 'AuthSession',
            'BackgroundOperation', 'BackgroundOperationResult', 'BatchApexErrorEvent', 'BrandingSet', 'BrandingSetProperty', 'BrandTemplate', 'BusinessProcess',
            'ClientBrowser', 'ColorDefinition', 'ConferenceNumber', 'CorsWhitelistEntry', 'CronJobDetail', 'CronTrigger', 'CspTrustedSite', 'CustomBrand',
            'CustomBrandAsset', 'CustomObjectUserLicenseMetrics', 'Dashboard', 'DashboardComponent', 'DashboardComponentFeed', 'DashboardFeed',
            'DataAssessmentFieldMetric', 'DataAssessmentMetric', 'DataAssessmentValueMetric', 'DataStatistics', 'DataType', 'Domain', 'DomainSite', 'FlexQueueItem',
            'FlowRecordRelation', 'FlowStageRelation', 'ForecastingAdjustment', 'ForecastingDisplayedFamily', 'ForecastingFact', 'ForecastingItem',
            'ForecastingOwnerAdjustment', 'ForecastingQuota', 'ForecastingShare', 'ForecastingType', 'ForecastingUserPreference', 'ForecastShare', 'IconDefinition',
            'IdpEventLog', 'InstalledMobileApp', 'LightningExperienceTheme', 'ListEmail', 'ListEmailChangeEvent', 'ListEmailRecipientSource', 'ListEmailShare', 'ListView',
            'ListViewChart', 'ListViewChartInstance', 'LoginGeo', 'LoginHistory', 'LoginIp', 'Macro', 'MacroHistory', 'MacroInstruction', 'MacroShare', 'NamedCredential',
            'NavigationLinkSet', 'NavigationMenuItem', 'OauthToken', 'OnboardingMetrics', 'PackageLicense', 'PermissionSetTabSetting', 'PlatformAction',
            'PlatformCachePartition', 'PlatformCachePartitionType', 'PresenceConfigDeclineReason', 'PresenceDeclineReason', 'ProcessInstance', 'ProcessInstanceHistory',
            'ProcessInstanceNode', 'ProcessInstanceStep', 'ProcessInstanceWorkItem', 'ProcessNode', 'Publisher', 'PushTopic',

            'VerificationHistory'
        };
        List<Schema.SObjectType> appSObjectTypes = new List<Schema.SObjectType>{
            Schema.ExternalSystem__c.SObjectType, Schema.ExternalSystemField__c.SObjectType, Schema.ExternalSystemInterface__c.SObjectType,
            Schema.MetadataField__c.SObjectType, Schema.MetadataRecordType__c.SObjectType, Schema.MetadataSObject__c.SObjectType
        };
        List<String> suffixes = new List<String>{'ChangeEvent', 'Feed', 'History', 'Share'};
        for(Schema.SObjectType appSObjectType : appSObjectTypes) {
            String baseSObjectDeveloperName = appSObjectType.getDescribe().getName();
            ignoredSObjectDeveloperNames.add(baseSObjectDeveloperName);

            for(String suffix : suffixes) {
                ignoredSObjectDeveloperNames.add(baseSObjectDeveloperName.replace('__c', suffix));
            }
        }

        return ignoredSObjectDeveloperNames;
    }

    private Map<String, MetadataSObject__c> getExistingSObjectTypesByDeveloperName() {
        Map<String, MetadataSObject__c> existingSObjectTypesByDeveloperName = new Map<String, MetadataSObject__c>();
        for(MetadataSObject__c metadataSObject : [SELECT Id, Name, DeveloperName__c, SystemHashCode__c, IsInScope__c FROM MetadataSObject__c]) {
            existingSObjectTypesByDeveloperName.put(metadataSObject.DeveloperName__c, metadataSObject);
        }
        return existingSObjectTypesByDeveloperName;
    }

    private Id getRecordTypeId(Schema.SObjectType sobjectType, String recordTypeDeveloperName) {
        return sobjectType.getDescribe().getRecordTypeInfosByDeveloperName().get(recordTypeDeveloperName).getRecordTypeId();
    }

    private String getNamespace(Schema.DescribeSObjectResult sobjectDescribe) {
        return this.getNameSpace(sobjectDescribe.getName());
    }

    private String getNamespace(Schema.DescribeFieldResult fieldDescribe) {
        return this.getNameSpace(fieldDescribe.getName());
    }

    private String getNameSpace(Schema.RecordTypeInfo recordTypeInfo) {
        return this.getNamespace(recordTypeInfo.getDeveloperName());
    }

    private String getNamespace(String fullDeveloperName) {
        Integer localNameIndex = fullDeveloperName
            .replace('__c', '')           // Custom objects & custom settings
            .replace('__e', '')           // Custom platform events
            .replace('__mdt', '')         // Custom metadata types
            .replace('__ChangeEvent', '') // Standard platform events
            .replace('__Feed', '')        // Chatter feed
            .replace('__History', '')     // History object
            .replace('__Share', '')       // Share object
            .indexOf('__');               // Now we can determine if there is a namespace

        return localNameIndex < 0 ? null : fullDeveloperName.substring(0, localNameIndex);
    }

    private String getPrimarySObjectDeveloperName(Schema.SObjectType sobjectType) {
        String separator   = sobjectType.getDescribe().isCustom() ? '__' : '';
        String replacement = sobjectType.getDescribe().isCustom() ? '__c' : '';

        List<String> platformFeatureSObjectSuffixes = new List<String>{'ChangeEvent', 'Feed', 'History', 'Share'};

        String parentSObjectDeveloperName;
        for(String platformFeatureSObjectSuffix : platformFeatureSObjectSuffixes) {
            if(!sobjectType.getDescribe().getName().endsWith(separator + platformFeatureSObjectSuffix)) continue;

            String currentSObjectDeveloperName = sobjectType.getDescribe().getName();
            parentSObjectDeveloperName = currentSObjectDeveloperName.replace(separator + platformFeatureSObjectSuffix, separator + replacement);
        }

        // ActivityHistory is a platform feature without a parent sobject
        if(sobjectType == Schema.ActivityHistory.SObjectType) parentSObjectDeveloperName = null;
        // OpportunityFieldHistory doesn't follow Salesforce's standard naming convention since OpportunityHistory also exists
        if(sobjectType == Schema.OpportunityFieldHistory.SObjectType) parentSObjectDeveloperName = Schema.Opportunity.SObjectType.getDescribe().getName();

        return parentSObjectDeveloperName;
    }

    private String getReferenceToValueString(Schema.DescribeFieldResult fieldDescribe) {
        List<String> values = new List<String>();
        for(Schema.SObjectType sobjectType : fieldDescribe.getReferenceTo()) {
            values.add(sobjectType.getDescribe().getName());
        }
        return String.join(values, '\n');
    }

    private String getPicklistValueString(Schema.SObjectField field) {
        String valueString = String.join(this.getPicklistValues(field), '\n');
        if(valueString.length() > field.getDescribe().getLength()) return 'Too many values';
        return valueString;
    }

    private List<String> getPicklistValues(Schema.SObjectField field) {
        Schema.DescribeFieldResult fieldDescribe = field.getDescribe();
        List<String> picklistValues = new List<String>();

        if(fieldDescribe.getPickListValues().isEmpty()) return picklistValues;

        for(Schema.PicklistEntry picklistEntry : fieldDescribe.getPickListValues()) {
            picklistValues.add(picklistEntry.getValue());
        }
        return picklistValues;
    }

}